name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Cache Rust toolchain
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/env
          ~/.rustup/settings.toml
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
        key: ${{ runner.os }}-rust-toolchain-${{ hashFiles('rust-toolchain.toml') }}

    - name: Set up Rust (1.42.0)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.42.0-x86_64-unknown-linux-gnu
        default: true
        override: true
        profile: minimal

    - name: Cache oj-verify testcases
      uses: actions/cache@v2
      with:
        path: .verify-helper/cache
        key: oj-verify-${{ hashFiles('verify/**/*.rs') }}

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify run --jobs 2
